services:
  fastapi_todo_database:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app_user
      POSTGRES_DB: app_db
      POSTGRES_PASSWORD: app_password
    ports:
      - "5432:5432"

  fastapi_todo_app:
    image: fastapi_todo_app
    build: .
    command: bash -c "poetry run alembic upgrade head && poetry run uvicorn --host 0.0.0.0 fastapi_todo.app:app"
    ports:
      - "8000:8000"
    depends_on:
      - fastapi_todo_database
    environment:
      DATABASE_URL: postgresql+psycopg://app_user:app_password@fastapi_todo_database:5432/app_db

volumes:
  pgdata: