name: Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: python install
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

